### ISSUE TITLE
Parsing error "offset":5.5 expecting integer.

### ISSUE THREAD

**Issue by caman9119** [kevinzetterstrom/forecast-android#3]
Here is the URL causing the issue: https://api.forecast.io/forecast/API_KEY/13.7199,80.2304 and in case the weather updates:

```{"latitude":13.7199,"longitude":80.2304,"timezone":"Asia/Kolkata","offset":5.5```

Error from onFailure:
```ERROR: java.lang.NumberFormatException: Expected an int but was 5.5 at line 1 column 79 path $.offset```

**Comment by caman9119** [comment]
This fixed it for me #4

**Comment by kevinzetterstrom** [comment]
Thanks!

**Comment by kevinzetterstrom** [comment]
Available in jcenter, version 1.1.1
