### ISSUE TITLE
Min SDK down to 15?

### ISSUE THREAD

**Issue by caman9119** [kevinzetterstrom/forecast-android#6]
Do you have any problem with bumping this down? I tested it locally and it works fine.

**Comment by kevinzetterstrom** [comment]
I chose level 16 purely out of OS market share. According to Google, right now, 16+ accounts for 96.6% of all Android devices. Level 15 accounts for only 1.6% of devices out there. I guess that asks the question then, is it really needed?

Besides that statistic, I don't have any issues lowering it, as this isn't really an Android library other than that it uses Android annotations which could easily be swapped out for jetbeans annotations. At the same time, I don't think it warrants a release on its own; I can get it done the next time I do release though (unless I just remove the Android dependency).

I will leave this open until then as a reminder.

**Comment by caman9119** [comment]
I went ahead and sent a PR for changes in my local fork. Feel free to take a look at the changes and do with it what you'd like.

**Comment by kevinzetterstrom** [comment]
I took your changes and added others - they are live in 1.2.0 on jCenter. Thanks!
